- image: "product (1).jpg"
  description: "جانانی"
  alt: "محصول ۱"

- image: "product (2).jpg"
  description: "زیرگلدان گرد"
  alt: "محصول ۲"

- image: "product (3).jpg"
  description: "زیرگلدان گرد بارنگُ‌های متنوع"
  alt: "محصول ۳"

- image: "product (4).jpg"
  description: "گلدان مستطیل "
  alt: "محصول ۴"

- image: "product (5).jpg"
  description: "گلدان چهارگوش"
  alt: "محصول ۵"

- image: "product (6).jpg"
  description: "گلدان چهارگوش رنگی"
  alt: "محصول ۶"

- image: "product (7).jpg"
  description: "زیرگلدان چهارگوش بارنگُ‌های متنوع"
  alt: "محصول ۷"

- image: "product (8).jpg"
  description: "گلدان چهارگوش بارنگُ‌های متنوع"
  alt: "محصول ۸"

- image: "product (9).jpg"
  description: "گلدان گرد رنگی"
  alt: "محصول ۹"

- image: "product (10).jpg"
  description: "گلدان کهکشان رنگی"
  alt: "محصول ۱۰"

- image: "product (11).jpg"
  description: "گلدان لاله "
  alt: "محصول ۱۱"

- image: "product (12).jpg"
  description: " گلدان گرد قهوه‌ای"
  alt: "محصول ۱۲"

- image: "product (13).jpg"
  description: "گلدان لاله با رنگ زیبا"
  alt: "محصول ۱۳"

- image: "product (14).jpg"
  description: "زیر لاله با زیری"
  alt: "محصول ۱۴"

- image: "product (15).jpg"
  description: "گلدان چهارگوش با زیری"
  alt: "محصول ۱۵"

- image: "product (16).jpg"
  description: "گلدان کهکشان با زیری"
  alt: "محصول ۱۶"

- image: "product (17).jpg"
  description: "جانانی کوچک و متوسط"
  alt: "محصول ۱۷"

- image: "product (18).jpg"
  description: "گلدان گرد "
  alt: "محصول ۱۸"

- image: "product (19).jpg"
  description: "ظرف غذا زنبور عسل "
  alt: "محصول ۱۹"